import Head from "next/head";
import Image from "next/image";
import Grids from "../components/Grids";
import SpinNav from "../components/SpinNav";
import Home from "../components/Home";

export default function Index() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta property="og:title" content="Title Here" />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="http://localhost:3000/" />
        <meta property="og:image" content="/.paintings" />
        <meta property="og:description" content="Description Here" />
        <meta property="og:site_name" content="Site Name" />
        <meta property="fb:admins" content="Facebook numeric ID" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
      {/* <Grids /> */}
      {/* <SpinNav /> */}
    </div>
  );
}
