import Head from "next/head";
import Image from "next/image";
import Grids from "../components/Grids";
import SpinNav from "../components/SpinNav";
import Home from "../components/Home";

export default function Index() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
      {/* <Grids /> */}
      {/* <SpinNav /> */}
    </div>
  );
}
